import { Request, Response } from 'express';
import orderService from '../services/order.service';
import { AppError } from '../middleware/errorHandler';

export const createOrder = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const order = await orderService.createOrder(req.user.userId, req.body);

  if (!order) {
    throw new AppError('Failed to create order', 500, 'ORDER_CREATION_FAILED');
  }

  res.status(201).json({
    success: true,
    message: 'Order created successfully',
    data: {
      order: {
        id: order.id,
        orderNumber: order.orderNumber,
        totalAmount: Number(order.totalAmount),
        paymentMethod: order.paymentMethod,
        paymentStatus: order.paymentStatus,
        orderStatus: order.orderStatus,
        items: order.items,
      },
      // Payment integration would go here
      payment: {
        gateway: order.paymentMethod,
        status: 'pending',
        // payment_url would be generated by payment gateway
      },
    },
  });
};

export const getMyOrders = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const filters = {
    page: req.query.page as number | undefined,
    limit: req.query.limit as number | undefined,
    status: req.query.status as string | undefined,
  };

  const result = await orderService.getUserOrders(req.user.userId, filters);

  res.status(200).json({
    success: true,
    data: result,
  });
};

export const getOrderDetails = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const { id } = req.params;
  const order = await orderService.getOrderDetails(id, req.user.userId);

  res.status(200).json({
    success: true,
    data: order,
  });
};

export const cancelOrder = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const { id } = req.params;
  const { reason } = req.body;

  const result = await orderService.cancelOrder(id, req.user.userId, reason);

  res.status(200).json({
    success: true,
    message: 'Order cancelled successfully',
    data: result,
  });
};


export const reorder = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const { id } = req.params;
  const result = await orderService.reorder(id, req.user.userId);

  const message = result.added.length
    ? `${result.added.length} item${result.added.length > 1 ? 's' : ''} added to your cart`
    : 'No items could be re-added';

  res.status(200).json({ success: true, message, data: result });
};
