import { Request, Response } from 'express';
import orderService from '../services/order.service';
import { AppError } from '../middleware/errorHandler';

export const createOrder = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const order = await orderService.createOrder(req.user.userId, req.body);

  if (!order) {
    throw new AppError('Failed to create order', 500, 'ORDER_CREATION_FAILED');
  }

  res.status(201).json({
    success: true,
    message: 'Order created successfully',
    data: {
      order: {
        id: order.id,
        orderNumber: order.orderNumber,
        totalAmount: Number(order.totalAmount),
        paymentMethod: order.paymentMethod,
        paymentStatus: order.paymentStatus,
        orderStatus: order.orderStatus,
        items: order.items,
      },
      // Payment integration would go here
      payment: {
        gateway: order.paymentMethod,
        status: 'pending',
        // payment_url would be generated by payment gateway
      },
    },
  });
};

export const getMyOrders = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const filters = {
    page: req.query.page as number | undefined,
    limit: req.query.limit as number | undefined,
    status: req.query.status as string | undefined,
  };

  const result = await orderService.getUserOrders(req.user.userId, filters);

  res.status(200).json({
    success: true,
    data: result,
  });
};

export const getOrderDetails = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const { id } = req.params;
  const order = await orderService.getOrderDetails(id, req.user.userId);

  res.status(200).json({
    success: true,
    data: order,
  });
};

export const cancelOrder = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const { id } = req.params;
  const { reason } = req.body;

  const result = await orderService.cancelOrder(id, req.user.userId, reason);

  res.status(200).json({
    success: true,
    message: 'Order cancelled successfully',
    data: result,
  });
};

export const getSellerPaymentDetails = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const { id } = req.params;
  const result = await orderService.getSellerPaymentDetails(id, req.user.userId);

  res.status(200).json({
    success: true,
    data: result,
  });
};

export const submitManualPayment = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const { id } = req.params;
  const result = await orderService.submitManualPayment(id, req.user.userId, req.body);

  res.status(200).json({
    success: true,
    message: 'Payment details submitted successfully. Awaiting seller confirmation.',
    data: result,
  });
};

export const confirmManualPayment = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const { id } = req.params;
  const { confirmed, disputeReason } = req.body;
  const result = await orderService.confirmManualPayment(id, req.user.userId, confirmed, disputeReason);

  res.status(200).json({
    success: true,
    message: confirmed ? 'Payment verified and confirmed' : 'Payment marked as disputed',
    data: result,
  });
};

export const getOrderMessages = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const { id } = req.params;
  const role = req.query.role as string | undefined;
  const result = await orderService.getOrderMessages(id, req.user.userId, role);

  res.status(200).json({
    success: true,
    data: result,
  });
};

export const sendOrderMessage = async (req: Request, res: Response) => {
  if (!req.user) {
    throw new AppError('Authentication required', 401, 'AUTH_REQUIRED');
  }

  const { id } = req.params;
  const { message, role, messageType, mediaUrl, duration } = req.body;

  if (!message && !mediaUrl) {
    throw new AppError('Message text or media is required', 400, 'MESSAGE_REQUIRED');
  }
  if (message !== undefined && (typeof message !== 'string' || message.length > 2000)) {
    throw new AppError('Message must be text of at most 2000 characters', 400, 'INVALID_MESSAGE');
  }
  if (messageType !== undefined && !['text', 'voice', 'image'].includes(messageType)) {
    throw new AppError('Invalid message type', 400, 'INVALID_MESSAGE_TYPE');
  }
  // Media is a link to an uploaded file, never an inline payload or script URL.
  if (mediaUrl !== undefined && (typeof mediaUrl !== 'string' || !/^(https?:\/\/|\/)/i.test(mediaUrl))) {
    throw new AppError('Invalid media link', 400, 'INVALID_MEDIA_URL');
  }
  if (duration !== undefined && (typeof duration !== 'number' || duration < 0 || duration > 3600)) {
    throw new AppError('Invalid duration', 400, 'INVALID_DURATION');
  }

  const result = await orderService.sendOrderMessage(id, req.user.userId, message || '', {
    role,
    messageType,
    mediaUrl,
    duration,
  });

  res.status(201).json({
    success: true,
    data: result,
  });
};


